### ISSUE TITLE
local installation fails

### ISSUE THREAD

**Issue by remisharrock** [cs-education/sysbuild#171]
Hi, I tried to follow the steps [here](https://github.com/cs-education/sysbuild/blob/master/.github/CONTRIBUTING.md#development-environment-set-up) without success:

**1**  seems OK:

```
$ npm --version
3.10.6
```

**2** seems OK:

```
$ bower --version
1.7.9
```

```
$ gulp --version
[17:33:59] CLI version 3.9.1
```

**3** forked and cloned correctly [my fork](https://github.com/remisharrock/sysbuild).
**4** ok
**5** seems ok, but I have three questions:
Q1: in [script.sh](https://github.com/cs-education/sysbuild/blob/master/scripts/setup.sh) , why do you use https://github.com/s-macke/jor1k.git  instead of  https://github.com/cs-education/jor1k.git ? 
Q2:  the folder jo1k has a .gitsubmodules with 

```
[submodule "sys"]
    path = sys
    url = https://github.com/s-macke/jor1k-sysroot.git
```

If I understand correctly the dependencies [here](https://github.com/cs-education/sysbuild/blob/master/.github/CONTRIBUTING.md#project-organization) , the url should be replaced with https://github.com/cs-education/jor1k/tree/sysbuild-stable  ?
Q3: should the [script.sh](https://github.com/cs-education/sysbuild/blob/master/scripts/setup.sh) also initialize the folder sys ? because it is not initialized after step **5**
**6** ok
**7** a few warnings:

```
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-react@^5.0.1 but none was installed.
```

**8** here I got an error:

```
$ gulp serve
[18:09:27] Failed to load external module babel-register
[18:09:27] Requiring external module babel-core/register
[18:09:35] Using gulpfile ~/sysbuild/webapp/gulpfile.babel.js
[18:09:35] Starting 'css:src'...
[18:09:36] Finished 'css:src' after 1.28 s
[18:09:36] Starting 'css:watch'...
[18:09:36] Finished 'css:watch' after 15 ms
[18:09:36] Starting 'serve:src'...
[18:09:37] Finished 'serve:src' after 108 ms
[18:09:37] Starting 'serve'...
[18:09:37] Finished 'serve' after 7.85 μs
[18:09:37] Server started http://localhost:8080
```

when I search for "Failed to load external module babel-register" I might be related to 
https://github.com/google/web-starter-kit/issues/878 
https://github.com/yeoman/generator-webapp/issues/356
**9** blank page with this console output:

```
GET http://localhost:8080/app/ga-tracker.js net::ERR_BLOCKED_BY_CLIENT
Uncaught Error: Script error for "app/ga-tracker"
http://requirejs.org/docs/errors.html#scripterror
Uncaught ReferenceError: window is not defined
Error at http://localhost:8080/bower_modules/requirejs/require.js:24: Uncaught ReferenceError: window is not defined
Master: Abort execution.
Uncaught Error: Kill master
```

**Comment by remisharrock** [comment]
update: on a clean install of npm etc, I get this message:

```
$ gulp serve
[02:19:26] Requiring external module babel-register
[02:19:29] Using gulpfile /Users/Shared/sharrock/sysbuild/webapp/gulpfile.babel.js
[02:19:29] Starting 'css:src'...
[02:19:29] Finished 'css:src' after 730 ms
[02:19:29] Starting 'css:watch'...
[02:19:29] Finished 'css:watch' after 14 ms
[02:19:29] Starting 'serve:src'...
[02:19:29] Finished 'serve:src' after 15 ms
[02:19:29] Starting 'serve'...
[02:19:29] Finished 'serve' after 1.69 μs
[02:19:30] Server started http://localhost:8080
ReferenceError: [BABEL] src/app/startup.js: Unknown option: /Users/Shared/sharrock/sysbuild/webapp/package.json.presets
    at Logger.error (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/Shared/sharrock/sysbuild/webapp/node_modules/babel-core/lib/api/node.js:120:43
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by prevosis** [comment]
I'll look into this. Your updated error is due to the fact that the JavaScript interpreter doesn't recognize [ES6 syntax](http://babeljs.io/) which is used throughout the project (i.e. "import fs from 'fs'" vs "var fs = require('fs')"). Babel is used to compile ES6 to the syntax recognized by Node.

**Comment by prevosis** [comment]
I'll look into this

**Comment by prevosis** [comment]
Seems fine to me, except my NPM is 3.8.9. Not sure why that would make a difference. If you're still concerned about this, try downloading a fresh copy of the repo and try again -- I had a lot of similar issues but everything seems to be in order at the moment
